"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = ['BreezeStyleSheets/dark.qss','time-tracker.config']
OPTIONS = {'includes': ['sip', 'PyQt5', 'PyQt5.QtCore', 'PyQt5.QtWidgets', 'sqlite3', 'datetime', 'datetime.datetime', 'datetime.timedelta', 'sys', 'os', 'os.path', 'configparser']}

setup(
    name="Time-Tracker",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
